#!/usr/bin/env python
# -*- coding: utf-8 -*-

def options(ctx):
    ctx.load('python')

def configure(ctx):
    print("configure python")
    ctx.load('python')
    ctx.check_python_version((2,6,0))
    ctx.check_python_headers()

def build(ctx):
    print('→ building from ' + ctx.path.abspath())

    # gets the path from the active virtualenv
    pybindings = ctx.shlib(
        source   = [ctx.path.find_resource('framecount_python.cpp'), ctx.path.find_resource('../frames.cpp')],
        target   = '_essentia_framecount',
        includes = ['..'],
        features = 'pyext',
        cxxflags = [ '-w' ],
        install_path = '${PYTHONDIR}',
        use      = 'framecount'
    )

    # FIXME: this doesn't install in the active virtualenv but in the system python...
    ctx.install_files('${PYTHONDIR}', ctx.path.ant_glob('framecount/**/*.py'),
                      relative_trick=True)
